# Setup
title: udoprog
url: https://udoprog.github.io
paginate: 5
baseurl: ""
permalink: /:categories/:year-:month-:day/:title.html

description: >
  A Rust enthusiast, working freelance to solve interesting problems.

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: John-John Tedro
  url: https://udoprog.github.io
  email: udoprog@tedro.se

# Custom vars
version: 3.0.0

github:
  user: udoprog
  repo: udoprog/udoprog.github.io
  url: https://github.com/udoprog/udoprog.github.io

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
