# Site settings
title: udoprog.github.io
email: johnjohn.tedro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm a Software Developer working at solving hard monitoring problems at Spotify.
baseurl: ""
url: "https://udoprog.github.io"
twitter_username: udoprog
github_username:  udoprog

excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown

paginate: 2
paginate_path: "/blog/page:num/"

comments:
  short_name: udoproggithubio
