# Permalinks
permalink:      /:categories/:year-:month-:day/:title.html

description: > # this means to ignore newlines until "baseurl:"
  A Software Engineer working with Monitoring @ Spotify.

# Setup
title:          Some(udoprog)
paginate:       5
url:            "https://udoprog.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         John-John Tedro
  url:          https://udoprog.github.io
  email:        udoprog@tedro.se

# Custom vars
version:        3.4.1
github:
  user: udoprog
  repo: https://github.com/udoprog/udoprog.github.io

twitter:
  user: udoprog

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - liquid_pluralize

excerpt_separator: <!-- more -->

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
