# Permalinks
permalink:      /:year-:month-:day/:title

description: > # this means to ignore newlines until "baseurl:"
  A Software Engineer working with Monitoring @ Spotify.

# Setup
title:          udoprog.github.io
paginate:       5
url:            "https://udoprog.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         John-John Tedro
  url:          https://udoprog.github.io
  email:        udoprog@tedro.se

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/udoprog/udoprog.github.io

# Plugins
plugins:
  - jekyll-paginate

excerpt_separator: <!-- more -->
