# Site settings
title: udoprog.github.io
email: udoprog@tedro.se
description: > # this means to ignore newlines until "baseurl:"
  A Software Engineer working with Monitoring @ Spotify.
baseurl: ""
url: "https://udoprog.github.io"
twitter_username: udoprog
github_username:  udoprog

excerpt_separator: <!-- more -->

# Build settings
markdown: kramdown

paginate: 2
paginate_path: "/blog/page:num/"

comments:
  short_name: udoproggithubio
